### PR TITLE
Support password and db number from configs

### PR DESCRIPTION
**Pull request by paunin**

### CODE REVIEW

**Comment by paunin** [comment]
BTW: Why do you recommend other solution instead of yours in the last release?... I can't see problems with this one... lets tune this one up... ;) 

Can't run tests though but I would drop them as non-required. It's all about configurations only.

**Comment by bkuhl** [comment]
Because the official redis approach would be more efficient than using this approach.

**Comment by paunin** [comment]
@bkuhl, I cant see here (https://github.com/cooperaj/laravel-redis-sentinel/tree/master/src/RedisSentinel/Laravel) anything better.... why do you say so... can you point the place that package uses  official redis approach, may be I'm blind a bit :D

**Comment by bkuhl** [comment]
Did you look into http://stackoverflow.com/questions/28309671/configuring-highly-available-redis-cluster-in-laravel/41686046#41686046 ?  There's a post there that talks about it.  My understanding is that with the approach described there this package is no longer needed.

**Comment by paunin** [comment]
I saw the article and I also so the code - nothing special, and dont support lumen54 ... so thats why I do ask:)  You package is fine agains that one

**Comment by paunin** [comment]
also trying this one - https://packagist.org/packages/monospice/laravel-redis-sentinel-drivers
looks good as well

**Pull request merged**
